POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Random Thoughts",
  "author": "Randy Random",
  "url": "https://randysblog.com/",
  "likes": 1100,
  "userId": "680c480c3d2cc875439c463c"
}
