POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1tMjAwMCIsImlkIjoiNjgxMTczNThlMmFiZGU0NjVjODEwNzZhIiwiaWF0IjoxNzQ1OTc0MTMzfQ.2x_c0Ty-NL9USxIwSVlIXuV8EYrHaqPyKb8-IuwBYkU

{
  "title": "Testi Testi",
  "author": "Testi Mies",
  "url": "https://testi-mies.com/",
  "likes": 100
}
