POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImxzMTk5NiIsImlkIjoiNjgwZDY1YTBkYzhiMmExOTgxZThhN2IyIiwiaWF0IjoxNzQ1NzEzOTI2fQ.u2UcLC-GBFO5O08O4LAvxHiuDF9-7Gxlw3H2eXb26mQ

{
  "title": "Random Thoughts",
  "author": "Randy Random",
  "url": "https://randysblog.com/",
  "likes": 1100
}
