POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoidHJ5X2F1dGgiLCJpZCI6IjY4MGJmYzIzN2Q4OTQ2MWExYjFhMmIxNyIsImlhdCI6MTc0NTYxNjY1M30.R99obCkNygLDraVUq4qNXSUDkJkAbBpAW_GyYJi4dWQ

{
    "content": "token was created with auth",
    "important": true
}
